image:https://musicdoc.github.io/logo.svg[logo,width="150",link="https://musicdoc.github.io"]

image:https://img.shields.io/github/license/musicdoc/musicdoc.svg?label=License["Apache License, Version 2.0",link=https://github.com/musicdoc/musicdoc/blob/master/LICENSE]
image:https://github.com/musicdoc/musicdoc/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/musicdoc/musicdoc/actions/workflows/build.yml"]

= MusicDoc Core

image:https://img.shields.io/maven-central/v/io.github.musicdoc/musicdoc-core.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.musicdoc]
image:https://javadoc.io/badge2/io.github.musicdoc/musicdoc-core/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.musicdoc/musicdoc-core]

This repository provides a Java library (artifactId `musicdoc-core`) with support for musical partitures with focus on https://musicdoc.github.io[MusicDoc format].

== Features

It offers the following features:

* model for musical partitures and all its elements such as `TonePitch`,`Rest`,`Tone`,`Interval`,`Chord`,`Clef`,`MusicalKey`,`Beat`,`Stave`,`Bar`,`TonalSystem`,`Partiture`,etc.
* reading (parsing) a partiture in https://musicdoc.github.io[MusicDoc] and other formats such as https://www.chordpro.org/[ChordPro], https://abcnotation.com/[ABC] and others.
* writing a partiture to https://musicdoc.github.io[MusicDoc] format.
* various musical operations including tansposing (both chromatic and diatonic), normalization, computing intervals, etc.

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.musicdoc</groupId>
  <artifactId>musicdoc-core</artifactId>
  <!-- <version>${musicdocVersion}</version> -->
</dependency>
```
Gradle Dependency:
```
implementation 'io.github.musicdoc:musicdoc-core:${musicdocVersion}'
```
For `${musicdocVersion}` please fill in the latest version that you can find in the badge above.

Module Dependency:
```java
  requires transitive io.github.musicdoc;
```

== Example

```java
TODO
```
